version: '3.1'

services:
  web:
    container_name: CyberTech
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
       - ./.docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
  
  php:
    image: php:7.4-apache
    ports:
      - 9999:80
    volumes:
      - ./src:/var/www/html/
  