version: '3.1'

services:
  web:
    container_name: CyberTechWeb
    build:
      context: .
    volumes:
       - ./.docker/000-default.conf:/etc/apache2/sites-available/000-default.conf

  cybertech:
    image: raviprakash1907/cybertech:latest
    ports:
      - 9999:80
    volumes:
      - ./src:/var/www/html/
